// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhmqktthewxcrhxibpsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobXFrdHRoZXd4Y3JoeGlicHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MzgwNjMsImV4cCI6MjA3MTQxNDA2M30.K9kIdsuTTBIhd1lJPsEC3IV153MpR14DYraRqwAHGsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});